name: Run Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install .[dev]

    - name: Check code formatting with black
      run: |
        source venv/bin/activate
        black . --check

    - name: Lint with flake8
      run: |
        source venv/bin/activate
        flake8 .

    - name: Run unit tests
      run: |
        source venv/bin/activate
        python -m unittest discover tests

  docker-run:
    runs-on: ubuntu-latest
    needs: docker-build
    name: Run Tasky CLI in Docker

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t tasky .

    - name: Run tasky CLI commands
      run: |
        docker run --rm tasky tasky add "This is a CI test"
        docker run --rm tasky tasky list
